### ISSUE TITLE
RTNETLINK answers: Invalid Argument

### ISSUE THREAD

**Issue by forkingmaster** [jeez/iproute2#1] opened 2018-12-14 05:46 UTC
Hi there,

I am working on time triggered send feature using ETF option. After installation of iproute2 package with ETF support, I am unable to schedule using ETF feature in i210.

I am getting the following errors:

- **RTNETLINK answers: Invalid Argument**
- **RTNETLINK answers: No such file or directory**

I have enabled ETF and CBS option in kernel and verified loaded modules. But still the above mentioned error persists when scheduling is loaded.
@jeez Any help on this would be appreciated!

**Comment by jeez** [comment] 2019-01-21 16:53
hi there, sorry for the delay.

Which version of iproute2 are you using? My fork here is rather old, you should probably be using the upstream tree at this point. The same applies to the kernel tree.

**Comment by forkingmaster** [comment] 2019-01-23 07:57
Currently, I am working on mainline Linux kernel 4.19.0 and using mainline iproute2 version 4.19 from kernel.org site.

I ensured that no module related to igb got stripped. When I try loading ETF, there already exists the symbolic link between the igb and sch_etf module. But the scheduling does not get applied on the network interface. System throws me the above mentioned two errors.

In few x86 architecture systems, ETF is working fine. But, in certain targets I am facing this issue.

**Comment by jeez** [comment] 2019-01-24 06:04
Can you please paste the exact tc commands you've been using? I'm assuming you've been using mqprio as your root qdisc, so I'd like to see how you are setting up that as well.

We had an issue with iproute2 and mqprio at some point, but I don't recall if it was on the 4.19 version or not.

**Comment by forkingmaster** [comment] 2019-01-25 02:58
Please find below the command used in our end:
**tc qdisc replace dev enp2s0 parent root mqprio num_tc 3 map 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@1 2@2 hw 0
tc qdisc add dev enp2s0 parent 100:1 etf offload delta 200000 clockid CLOCK_TAI**

**Comment by jeez** [comment] 2019-01-26 01:00
I'm assuming the first error you listed shows up when you run the mqprio command, right?

What happens if you try the below instead:

  1) First, setup mqprio as the root qdisc:
	$ sudo tc qdisc replace dev IFACE parent root handle 100 mqprio	\
			num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2	\
			queues 1@0 1@1 2@2 hw 0

    2) Then setup etf with:
	$ sudo tc qdisc add dev enp2s0 parent 100:1 etf 	\
			offload clockid CLOCK_TAI delta 200000

I suspect something is off with your mqprio line, either the fact that you are missing a handle or it doesn't like the mapping, not sure... let's try the one above which is known to work.

**Comment by forkingmaster** [comment] 2019-01-28 05:16
> I'm assuming the first error you listed shows up when you run the mqprio command, right?
> 
> What happens if you try the below instead:
> 
> 1. First, setup mqprio as the root qdisc:
>    $ sudo tc qdisc replace dev IFACE parent root handle 100 mqprio	
>    num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2	
>    queues 1@0 1@1 2@2 hw 0

I tried setting up this command. But still the same issue exists (RTNETLINK answers: Invalid argument). Any idea on what could be wrong?

**Comment by jeez** [comment] 2019-01-29 05:18
Yeah, so I think that was the bug on mqprio I mentioned. It was fixed on upstream already, I'm surprise it wasn't backported to the 4.19 version.

@vcgomes can you please help refreshing my memory here on the above?

**Comment by vcgomes** [comment] 2019-01-29 17:54
Hi Jesus,

Jesus Sanchez-Palencia <notifications@github.com> writes:

> Yeah, so I think that was the bug on mqprio I mentioned. It was fixed
> on upstream already, I'm surprise it wasn't backported to the 4.19
> version.
>
> @vcgomes can you please help refreshing my memory here on the above?

That bug got fixed in iproute2 version 4.18.

Yeah, it could that the reporter is running an old iproute2 version on
their machines.

Good catch. I forgot about that bug.

**Comment by forkingmaster** [comment] 2019-01-30 05:23
Hello Gomes,

I am running latest iproute2 version v4.19.0 (https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.19.0.tar.gz) downloaded from official website.

As per the above discussion, I should not face issues in this particular version but still I am facing it.

**Comment by vcgomes** [comment] 2019-01-30 18:00
Is there any output in dmesg? Running it under strace (and putting the output somewhere we can take a look) might be a good idea as well (I like to pass "-yy" to it, to give more information about syscalls)

I just noticed that some(all?) of the machines giving problems aren't x86, so perhaps there's some wrong assumptions about size/alignment on either iproute2 or the kernel? But if that's so, it makes harder to reproduce it here.

What might be interesting as well is to try another qdiscs and see if they give any problems as well: that might help root cause the issue. 'netem' is a good one to try.

**Comment by forkingmaster** [comment] 2019-02-04 04:49
So far, problems we face are in x86 systems. 

In "dmesg", I am not able to identify any error message regarding this issue. For your reference, I have attached the dmesg output and strace prints as well.
As per your suggestion, i tried loading 'netem' qdisc and that works fine for me.

[dmesgOutput.txt](https://github.com/jeez/iproute2/files/2826552/dmesgOutput.txt)
[straceOutput.txt](https://github.com/jeez/iproute2/files/2826553/straceOutput.txt)
[straceOutput_2.txt](https://github.com/jeez/iproute2/files/2826551/straceOutput_2.txt)

**Comment by jimenaCabrejas** [comment] 2019-02-06 09:20
Hi, I'm facing the same problem.

I am working on Linux kernel 4.20.0 and I am running the latest iproute2 version v4.19.0 (the same as forkingmaster). My system is x86_64. I have verified that the modules are loaded. 

But when I execute the command 
_$ sudo tc qdisc replace dev IFACE parent root handle 100 mqprio num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@1 2@2 hw 0_
I also get the error 
**RTNETLINK answers: Invalid Argument**

Other qdiscs work fine.

**Comment by jeez** [comment] 2019-02-06 17:00
That's unexpected. I have no way to test this anytime soon, @vcgomes (or not before end of next week, at least). What about you?

**Comment by vcgomes** [comment] 2019-02-06 18:24
I think I found the possible reason of this issue. The system that @forkingmaster is using has only two cores, and igb uses that as a bound of the number of queues that can be allocated. So the command line that tries to assign traffic to the four queues (that exists in the HW) fails.

Can you try this command:
```
$ sudo tc qdisc replace dev IFACE parent root handle 100 mqprio num_tc 2 map 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 queues 1@0 1@1 hw 0
```
I this works, then my hypothesis could be correct. But if it is, I don't have a good solution for this. In general, you have at least as much queues as cores so the kernel can assign different interrupt handlers to different cores, so transmission can scale on the order of the number cores. So changing that policy might be problematic for the current use cases.

But I am wondering :-) Let's see if the command above works, then we start from there.

Sorry it took so long for me to notice this.

**Comment by jimenaCabrejas** [comment] 2019-02-07 10:31
@vcgomes That was it! That command works in my system (I have only two cores too).

**Comment by forkingmaster** [comment] 2019-02-07 13:43
> But I am wondering :-) Let's see if the command above works, then we start from there.

Hey @vcgomes, thank you, You made my day, the solution works for me!!
But I would like to know that if this is a workaround? Or is there any way to use ETF like how it is being used on four core systems?

**Comment by vcgomes** [comment] 2019-02-07 18:31
forkingmaster <notifications@github.com> writes:

>> But I am wondering :-) Let's see if the command above works, then we start from there.
>
> Hey @vcgomes, thank you, You made my day, the solution works for me!!
> But I would like to know that if this is a workaround? Or is there any
> way to use ETF like how it is being used on four core systems?

I wouldn't say that this is a workaround. But this is another totally
different configuration that instead of mapping different types of
traffic to 4 queues, maps to only 2.

Not sure that I understand your question. You will still be able to use
ETF on queue 0 (for example), but all the rest of the traffic would go
to queue 1. In practical terms, you would have one queue for traffic
that's SO_TXTIME aware, and one queue for the rest.

Did I get your question right?

**Comment by forkingmaster** [comment] 2019-02-07 20:15
Yes I got your point. Thanks for your support on getting this resolved.

**Closed as completed** 2019-02-11 22:53 UTC

**Comment by vcgomes** [comment] 2019-04-18 22:44
Just a quick update, I was just made aware of a much better solution to this issue. You can do something like this:

```
$ ethtool -L <IFACE> combined 4
```

To "force" the allocation of some number of queues. See if it works for your use-cases.

**Comment by jimenaCabrejas** [comment] 2019-04-24 07:53
Yes, that solution works for my use-case.

Thank you!

**Comment by kcn21** [comment] 2021-10-21 11:50
> Just a quick update, I was just made aware of a much better solution to this issue. You can do something like this:
> 
> ```
> $ ethtool -L <IFACE> combined 4
> ```
> 
> To "force" the allocation of some number of queues. See if it works for your use-cases.

Hello @vcgomes , I  got "Cannot set device channel parameters: Invalid argument"
with the help of your command I able to execute mqprio qdisc in one PC. but in other PC it give me error which I stated above. 
 
The PC in which mqprio executed properly gave the following output for ethtool -l IFACE command:

Channel parameters for Interface_Name:
Pre-set maximums:
RX: 0
TX: 0
Other: 1
Combined: 4
Current hardware settings:
RX: 0
TX: 0
Other: 1
Combined: 4

The PC in which I got error has following output for ethtool -l IFACE command:

Channel parameters for enp4s0:
Pre-set maximums:
RX: 4
TX: 1
Other: 0
Combined: 0
Current hardware settings:
RX: 4
TX: 1
Other: 0
Combined: 0

but I can't able to change the parameters of the channel 
when I executed the command 
 ethtool -L <IFACE> combined 4
"Cannot set device channel parameters: Invalid argument" error came

please help. 

Thanks, 
Kunj.
